/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    bookings: Booking;
    practices: Practice;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    practices: PracticesSelect<false> | PracticesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
    home: Home;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Demandes reçues par le formulaire du site. Passez le statut à « Confirmée » pour prévenir le client par e-mail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  status: 'nouveau' | 'confirme' | 'sans-suite' | 'archive';
  /**
   * Date et heure du rendez-vous, indiquées au client dans l’e-mail de confirmation.
   */
  slot?: string | null;
  /**
   * Ajouté à l’e-mail de confirmation ou de refus. Facultatif.
   */
  messageToClient?: string | null;
  /**
   * L’e-mail part quand le statut passe à « Confirmée » ou « Refusée / sans suite ».
   */
  notifyClient?: boolean | null;
  notifiedAt?: string | null;
  notifiedStatus?: string | null;
  notifyError?: string | null;
  /**
   * Visible uniquement dans l’administration.
   */
  note?: string | null;
  name: string;
  email: string;
  phone?: string | null;
  motif: string;
  mode: 'cabinet' | 'visio' | 'telephone';
  day: string;
  window: 'matin' | 'apres-midi' | 'fin-journee';
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les cartes de la section « Domaines ». L’ordre croissant définit l’ordre d’affichage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practices".
 */
export interface Practice {
  id: number;
  title: string;
  icon: 'family' | 'work' | 'criminal' | 'property';
  /**
   * Facultatif. Format paysage conseillé (3:2). Sans image, un fond bleu avec l’icône est affiché.
   */
  image?: (number | null) | Media;
  text: string;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos et images du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lue par les lecteurs d’écran. Ex. : « Portrait de Maître Marchand ».
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    portrait?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'practices';
        value: number | Practice;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  status?: T;
  slot?: T;
  messageToClient?: T;
  notifyClient?: T;
  notifiedAt?: T;
  notifiedStatus?: T;
  notifyError?: T;
  note?: T;
  name?: T;
  email?: T;
  phone?: T;
  motif?: T;
  mode?: T;
  day?: T;
  window?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practices_select".
 */
export interface PracticesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  image?: T;
  text?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        portrait?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Identité, coordonnées et informations légales du cabinet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  name: string;
  /**
   * Ex. : Maître Élise Marchand
   */
  lawyer: string;
  /**
   * 2 ou 3 lettres, affichées dans la barre et le portrait.
   */
  monogram?: string | null;
  /**
   * Ex. : Avocate à Paris
   */
  title?: string | null;
  barreau?: string | null;
  /**
   * Format portrait conseillé (4:5). Sans photo, un portrait illustré est affiché.
   */
  portrait?: (number | null) | Media;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  phone?: string | null;
  email?: string | null;
  hours?:
    | {
        days: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. : un jour ouvré. Affiché dans la page : ne promettez que ce que vous tenez.
   */
  responseTime?: string | null;
  availability?: {
    /**
     * Les autres jours ne sont pas proposés.
     */
    weekdays?: ('1' | '2' | '3' | '4' | '5' | '6' | '0')[] | null;
    closedDates?:
      | {
          date: string;
          reason?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * 0 = le jour même peut être proposé ; 1 = à partir de demain ; 2 = à partir d’après-demain…
     */
    minNoticeDays?: number | null;
    daysShown?: number | null;
  };
  siret?: string | null;
  vat?: string | null;
  insurer?: string | null;
  hosting?: string | null;
  mediator?: string | null;
  /**
   * Ex. : 12 mois
   */
  retention?: string | null;
  updated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les textes de chaque section de la page d’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    eyebrow?: string | null;
    title: string;
    lead?: string | null;
    highlights?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    title?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    facts?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Numérotées automatiquement dans l’ordre.
   */
  steps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  fees?: {
    title?: string | null;
    lead?: string | null;
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  booking?: {
    title?: string | null;
    lead?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  name?: T;
  lawyer?: T;
  monogram?: T;
  title?: T;
  barreau?: T;
  portrait?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  phone?: T;
  email?: T;
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  responseTime?: T;
  availability?:
    | T
    | {
        weekdays?: T;
        closedDates?:
          | T
          | {
              date?: T;
              reason?: T;
              id?: T;
            };
        minNoticeDays?: T;
        daysShown?: T;
      };
  siret?: T;
  vat?: T;
  insurer?: T;
  hosting?: T;
  mediator?: T;
  retention?: T;
  updated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        highlights?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        quote?: T;
        facts?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  fees?:
    | T
    | {
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  booking?:
    | T
    | {
        title?: T;
        lead?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}